# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DsriIdIXCNLmdes9FWjDK4QRs4DnWfV-
"""

import os

BASE_DIR = os.path.dirname(os.path.dirname(__file__))

DATA_RAW = os.path.join(BASE_DIR, "data/raw")
DATA_PICKLE = os.path.join(BASE_DIR, "data/pickle")
MODELS_DIR = os.path.join(BASE_DIR, "models")
