# -*- coding: utf-8 -*-
"""explain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AqjHGbrFAHeVUDLz9KDrf4wDSx18Cn34
"""

import shap

def explain_model(model, X_test, feature_names):
    explainer = shap.TreeExplainer(model)
    shap_values = explainer.shap_values(X_test)
    shap.summary_plot(shap_values, X_test, feature_names=feature_names)