# -*- coding: utf-8 -*-
"""featurize_protein.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zGzK7c2hJIBnQrSCUZSnhlYKcGFptuU6
"""

import numpy as np
from collections import Counter
import itertools
import requests

AA = "ACDEFGHIKLMNPQRSTVWY"

def load_fasta(uniprot_id):
    url = f"https://rest.uniprot.org/uniprotkb/{uniprot_id}.fasta"
    fasta = requests.get(url).text
    seq = "".join(line.strip() for line in fasta.split("\n") if not line.startswith(">"))
    return seq

def aa_composition(seq):
    counts = Counter(seq)
    total = len(seq)
    return np.array([counts[a] / total for a in AA])

def kmer_counts(seq, k=2):
    kmers = ["".join(p) for p in itertools.product(AA, repeat=k)]
    counter = Counter(seq[i:i+k] for i in range(len(seq)-k+1))
    total = len(seq)-k+1
    return np.array([counter[km]/total for km in kmers])

def featurize_protein(uniprot_id="P00533"):
    seq = load_fasta(uniprot_id)
    aa = aa_composition(seq)
    k2 = kmer_counts(seq, k=2)
    return np.hstack([aa, k2])