# -*- coding: utf-8 -*-
"""featurize_molecule.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IzW3CVJrMS8asKm1jpwaEf-OCHGXAlFR
"""

import numpy as np
from rdkit import Chem
from rdkit.Chem import rdFingerprintGenerator, Descriptors

morgan_gen = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=1024)

def smiles_to_morgan(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None
    return list(morgan_gen.GetFingerprint(mol))

def compute_descriptors(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None
    return [
        Descriptors.MolWt(mol),
        Descriptors.MolLogP(mol),
        Descriptors.TPSA(mol),
        Descriptors.NumHDonors(mol),
        Descriptors.NumHAcceptors(mol),
        Descriptors.NumRotatableBonds(mol)
    ]