# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hTlm0zoG_vt4Fr4wB7PPruAhRgka5rvF
"""

import joblib
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
import numpy as np

def train_rf(X, y, save_path):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    model = RandomForestRegressor(
        n_estimators=600,
        n_jobs=-1,
        random_state=42
    )
    model.fit(X_train, y_train)

    preds = model.predict(X_test)

    rmse = np.sqrt(((preds - y_test)**2).mean())
    print("RF RMSE:", rmse)

    joblib.dump(model, save_path)
    print(f"Model saved to: {save_path}")

    return model